apiVersion: v1
kind: Service
metadata:
  name: webcolor
  labels:
    app: webcolor
spec:
  selector:
    app: webcolor
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31900
  type: NodePort
---
### Necessario incluir Service Monitor para poder monitorar via Prometheus ###
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webcolor
  labels:
    release: prometheus-grafana   # importante, igual ao do conversao
spec:
  selector:
    matchLabels:
      app: webcolor               # tem que bater com o label do Service
  endpoints:
    - port: http                  # tem que bater com o "name:" da porta no Service
      path: /metrics
      interval: 15s
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webcolor-canary
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
#     annotations: -- Nao precisa de annotations pq o Prometheus é Operator, sendo assim, via Service Monitor
#        prometheus.io/scrape: 'true'
#        prometheus.io/path: '/metrics'
#        prometheus.io/port: '80'
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-color:blue
        imagePullPolicy: Always
        ports:
          - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - analysis:
          templates:
          - templateName: webcolor-success
      - setWeight: 75
      - analysis:
          templates:
          - templateName: webcolor-success
      - setWeight: 100







